### ISSUE TITLE
awx 11 failure on centos 8

### ISSUE THREAD

**Issue by Lobout** [MrMEEE/awx-build#238]
slight package conflict.  on a clean build of centos8 that installs the insights client there is a python package conflict

Installing AWX-RPM
Error:
 Problem: package insights-client-3.0.5-4.el8.noarch requires python3-PyYAML, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.1.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - package ansible-awx-11.2.0-2.1.x86_64 requires python3-pyyaml = 5.3.1, but none of the providers can be installed
  - conflicting requests
  - problem with installed package insights-client-3.0.5-4.el8.noarch

**Comment by MrMEEE** [comment]
Did you use the awx-setup script?

What requirements to pyyaml does insights-client have?

**Comment by MrMEEE** [comment]
And thank you for testing and giving feedback

**Comment by Lobout** [comment]
i will try and do a base install of centos.  I am testing this with a vm image i created.  I believe the image was built using the "server with gui" options.  I have modifed the awx-setup script to account for this am and testing this fix as well as fixing a couple minor centos/rhelos8 specific issues I saw that were not accounted for. (pertaining to the postgress setup)  I'll post my changes after i finish testing.

**Comment by MrMEEE** [comment]
Great.. I'm doing a new build right now.. I think a lot of the CentOS7 issues will be fixed there.. it will be up in about ½ hour...

**Comment by Lobout** [comment]
oops i think you broke the build..... ;-)

Installing AWX-RPM
Error:
 Problem: conflicting requests
  - nothing provides python36-rpm needed by ansible-awx-11.2.0-4.2.x86_64

**Comment by Lobout** [comment]
> oops i think you broke the build..... ;-)
> 
> Installing AWX-RPM
> Error:
> Problem: conflicting requests
> 
> * nothing provides python36-rpm needed by ansible-awx-11.2.0-4.2.x86_64

Build must not have been finished.   I now have a working install of awx 11 on centos8.  find attached my awx-setup script for the changes made.
[awx-setup.zip](https://github.com/MrMEEE/awx-build/files/4578637/awx-setup.zip)

**Comment by Lobout** [comment]
I will test against RH 8 install tomorrow.

**Comment by MrMEEE** [comment]
Ok.. thanks.. could you please retry against CentOS8? I think that we have fixed alot of the same stuff (remember to fetch the newest awx-setup script)..

Also, pull requests with the changes would be really nice :)

**Comment by Lobout** [comment]
> Ok.. thanks.. could you please retry against CentOS8? I think that we have fixed alot of the same stuff (remember to fetch the newest awx-setup script)..
> 
> Also, pull requests with the changes would be really nice :)

i submitted a pull request for you.  wasn't thinking last night when i did the work.

**Comment by MrMEEE** [comment]
You have submitted against the wrong fork :)..

Can you change it to:

https://github.com/MrMEEE/awx-rpm

Remember to rebase first...

Thanks a lot

**Comment by Lobout** [comment]
current build still shows the same issues. 

1.  package conflicts (this is obviously not a major issue as long as the correct os build is used)


Installing AWX-RPM
Error:
 Problem: package insights-client-3.0.5-4.el8.noarch requires python3-PyYAML, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.1.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - package ansible-awx-11.2.0-11.1.x86_64 requires python3-pyyaml = 5.3.1, but none of the providers can be installed
  - conflicting requests
  - problem with installed package insights-client-3.0.5-4.el8.noarch

2.  SCL is not included in centos8
sudo: scl: command not found
warning: /var/cache/dnf/epel-6519ee669354a484/packages/pwgen-2.08-3.el8.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 2f86d6a1: NOKEY
Importing GPG key 0x2F86D6A1:
 Userid     : "Fedora EPEL (8) <epel@fedoraproject.org>"

I changed the code the following:
if int(osversion) == 7:
         print(os.popen('sudo -u postgres scl enable rh-postgresql10 "createuser -S awx && createdb -O awx awx"').read())

to this to fix the issue:
if int(osversion) == 7:
         print(os.popen('sudo -u postgres scl enable rh-postgresql10 "createuser -S awx && createdb -O awx awx"').read())
       else:
         print(os.popen('sudo -u postgres createuser -S awx').read())
         print(os.popen('sudo -u postgres createdb -O awx awx').read())

**Comment by Lobout** [comment]
> You have submitted against the wrong fork :)..
> 
> Can you change it to:
> 
> https://github.com/MrMEEE/awx-rpm
> 
> Remember to rebase first...
> 
> Thanks a lot

i'm not a big user of gihub, i can't remember how to rebase through the browser... lol

**Comment by Lobout** [comment]
saw your commit with the postgres changes.  taking my package conflict out of the picture, the only thing that i needed to account for is the lack of having the following packages installed.

libcurl-devel
krb5-devel.x86_64

Without these packages the venv fails to get built.

After making sure these are installed, the install completes, but when you do an about on the build it does not show the ansible version installed.  If i then install ansible, and refresh the page, the ansible version shows up.

**Comment by MrMEEE** [comment]
I added the packages as dependencies to ansible-awx instead.. 

I will take a look at the version stuff

**Comment by Lobout** [comment]
> I added the packages as dependencies to ansible-awx instead..
> 
> I will take a look at the version stuff

ran through everything based on your setup script and everything installs.  I have not tested functionality yet, the only thing i currently see is the version information still does not show the ansible version installed.  If i install ansible (yum install ansible) the version information then shows

 ______________ 
<  AWX 11.2.0  >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)      A )\/\
                ||----w |
                ||     ||

Ansible unknown
Copyright © 2019 Red Hat, Inc.
Visit Ansible.com for more information.

**Comment by ghost** [comment]
/root/awx-setup -i
This is going to install AWX-RPM and all dependencies.. This installer is meant to be easy, not customizable..
Check https://awx.wiki for advanced install methods and more info..
Do you want to continue?  [y/N] y
Setting up AWX-RPM
Configuring SELinux

ValueError: Port tcp/8050 already defined

Configuring Firewall (Disabling for now/TODO)

Configure Repositories
Adding EPEL

Adding AWX-RPM Repo
Installing Redis

Installing PostgreSQL

Installing Memcached

Installing NGINX

Installing AWX-RPM
Error:
 Problem: problem with installed package vdo-6.2.5.74-14.el8.x86_64
  - package vdo-6.2.5.74-14.el8.x86_64 requires python3-PyYAML >= 3.10, but none of the providers can be installed
  - cannot install both python3-pyyaml-5.3.1-4.14.x86_64 and python3-pyyaml-3.12-12.el8.x86_64
  - package ansible-awx-11.2.0-20.12.x86_64 requires python3-pyyaml = 5.3.1, but none of the providers can be installed
  - conflicting requests

Initialising PostgreSQL
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit postgresql
 * Initializing database in '/var/lib/pgsql/data'
ERROR: Data directory /var/lib/pgsql/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_postgresql.log

Starting PostgreSQL

Creating AWX postgreSQL user and Database
could not change directory to "/root": Permission denied
createuser: creation of new role failed: ERROR:  role "awx" already exists

could not change directory to "/root": Permission denied
createdb: database creation failed: ERROR:  database "awx" already exists

Installing pwgen

Generating Secret key
/bin/sh: /etc/tower/SECRET_KEY: No such file or directory

Initial database migration
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Creating Admin user
sudo: unknown user: awx
sudo: unable to initialize policy plugin

Adding example data and registering AWX-RPM Instance in database
sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

sudo: unknown user: awx
sudo: unable to initialize policy plugin

Installing NGINX Configuration
/bin/cp: cannot stat '/usr/share/doc/ansible-awx/nginx.conf.example': No such file or directory

Configuring Redis
gpasswd: user 'awx' does not exist

Creating initial Ansible VENV
/bin/sh: awx-create-venv: command not found

Locking package versions for AWX-RPM and dependencies
Traceback (most recent call last):
  File "/root/awx-setup", line 385, in <module>
    main(sys.argv[1:])
  File "/root/awx-setup", line 316, in main
    with open("/usr/share/doc/ansible-awx/awx-locks.txt", "r") as a_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/ansible-awx/awx-locks.txt'



I am receiving this error in centos8.
