### ISSUE TITLE
Unable to start after Upgrading to 2.1

### ISSUE THREAD

**Issue by negesti** [MrMEEE/awx-build#52]
To restart awx after upgrading from 2.0 to 2.1 some some additional manual steps are required

1. when running ``sudo -u awx /opt/awx/bin/awx-manage makemigrations`` you have to merge the migrations
1. The folder /var/log/tower is missing and must be created manually
1. update the version in /var/lib/awx/.tower_version 
from ``2.1.0.58`` to ``2.1.0``

```
mkdir /var/log/tower
chown root:awx /var/log/tower
chmod 770 /var/log/tower

echo "2.1.0" >> /var/lib/awx/.tower_version

```

**Comment by angystardust** [comment]
Here, after the upgrade, both **awx-celery-beat** and **awx-celery-worker** fail to start:

```
Nov 06 19:59:17 empl-awx01.em.corp systemd[1]: Starting AWX Celery beat service...
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: Traceback (most recent call last):
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/bin/celery", line 11, in <module>
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: sys.exit(main())
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: _main()
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: cmd.execute_from_commandline(argv)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: super(CeleryCommand, self).execute_from_commandline(argv)))
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: argv = self.setup_app_from_commandline(argv)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: self.app = self.find_app(app)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 501, in find_app
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: return find_app(app, symbol_by_name=self.symbol_by_name)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/utils.py", line 378, in find_app
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: symbol_by_name=symbol_by_name, imp=imp,
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/utils.py", line 362, in find_app
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: sym = imp(app)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: return imp(module, package=package)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: __import__(name)
Nov 06 19:59:18 empl-awx01.em.corp celery[109531]: ImportError: No module named celery
Nov 06 19:59:18 empl-awx01.em.corp systemd[1]: awx-celery-beat.service: main process exited, code=exited, status=1/FAILURE
Nov 06 19:59:18 empl-awx01.em.corp systemd[1]: Unit awx-celery-beat.service entered failed state.
Nov 06 19:59:18 empl-awx01.em.corp systemd[1]: awx-celery-beat.service failed.
```
```
Nov 06 19:59:18 empl-awx01.em.corp systemd[1]: Starting AWX Celery worker service...
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: Traceback (most recent call last):
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/bin/celery", line 11, in <module>
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: sys.exit(main())
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: _main()
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: cmd.execute_from_commandline(argv)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: super(CeleryCommand, self).execute_from_commandline(argv)))
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: argv = self.setup_app_from_commandline(argv)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: self.app = self.find_app(app)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/bin/base.py", line 501, in find_app
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: return find_app(app, symbol_by_name=self.symbol_by_name)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/utils.py", line 378, in find_app
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: symbol_by_name=symbol_by_name, imp=imp,
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/app/utils.py", line 362, in find_app
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: sym = imp(app)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/opt/awx/embedded/lib/python2.7/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: return imp(module, package=package)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: __import__(name)
Nov 06 19:59:19 empl-awx01.em.corp celery[109540]: ImportError: No module named celery
Nov 06 19:59:19 empl-awx01.em.corp systemd[1]: awx-celery-worker.service: main process exited, code=exited, status=1/FAILURE
Nov 06 19:59:19 empl-awx01.em.corp systemd[1]: Unit awx-celery-worker.service entered failed state.
Nov 06 19:59:19 empl-awx01.em.corp systemd[1]: awx-celery-worker.service failed.

```

**Comment by MrMEEE** [comment]
@negesti Thanks for the info, it will be fixed in the next build.. (building right now)..

@angystardust Apparently the AWX people as switched away from celery.. This has been fixed in the next build (on it's way)

New build is: 2.1.0.74-2.el7

**Comment by angystardust** [comment]
Thanks @MrMEEE. I successfully upgraded to 2.1.0.74-1.el7 and cherry-picked the _awx-dispatcher.service_ systemd service. Now I can login again in the AWX dashboard :+1: 
But now, when I launch a JT, the page is not auto-refreshing anymore. I need to manually reload the page to get the status of the job :(

**Comment by MrMEEE** [comment]
@angystardust This means 99% that websockets are not working.. 

Usually fixed by:

1. Restarting awx-web and awx-daphne
2. Clearing cache in browser

Hope that will fix it.. It works here :).. (Certified on my machine)

**Comment by angystardust** [comment]
Thanks for the trick! I've restarted all the awx stack and cleaned up the cache: now it works again :confetti_ball:

**Comment by MrMEEE** [comment]
Perfect... thanks for the feedback

**Comment by negesti** [comment]
just updated to 2.1.0.74 and still facing the tower version error
> Missing or incorrect metadata for Tower version.  Ensure Tower was installed using the setup playbook." + tower_version)
Exception: Missing or incorrect metadata for Tower version.  Ensure Tower was installed using the setup playbook

I had to update the version in var lib again

``echo "2.1.0" > /var/lib/awx/.tower_version``

Note: I had two > in my first post ;)

**Comment by MrMEEE** [comment]
@negesti The fixed version is awx-2.1.0.74-2.el7.x86_64

awx-2.1.0.74-1.el7.x86_64 still have the issues.. 

I think it's almost done building..

**Comment by negesti** [comment]
@MrMEEE  sry, only got the mail from yum-cron and have only checked the 0.74 (without the -2)
